// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDbContext;

#nullable disable

namespace WebDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115141202_baseInfoUpdate")]
    partial class baseInfoUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebDbContext.DbEntity.BaseEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("playerId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("baseEntityDbSet");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.HeroEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("agility")
                        .HasColumnType("int");

                    b.Property<Guid?>("armorid")
                        .HasColumnType("char(36)");

                    b.Property<int>("charisma")
                        .HasColumnType("int");

                    b.Property<int>("currentHp")
                        .HasColumnType("int");

                    b.Property<bool>("inModule")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("intelect")
                        .HasColumnType("int");

                    b.Property<bool>("isAlive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("maxHp")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("strong")
                        .HasColumnType("int");

                    b.Property<Guid?>("weaponid")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.HasIndex("armorid");

                    b.HasIndex("weaponid");

                    b.ToTable("heroDbSet");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.ItemEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<Guid?>("PlayerEntityid")
                        .HasColumnType("char(36)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("PlayerEntityid");

                    b.ToTable("ItemEntity");

                    b.HasDiscriminator().HasValue("ItemEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebDbContext.DbEntity.Modules.ModuleEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("lvl")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("moduleDbSet");

                    b.HasDiscriminator().HasValue("ModuleEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebDbContext.DbEntity.PlayerEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("baseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("gameFraction")
                        .HasColumnType("int");

                    b.Property<int>("lvl")
                        .HasColumnType("int");

                    b.Property<int>("money")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("xp")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("playerDbSet");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.UserEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("hPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("userDbSet");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.ArmorEntity", b =>
                {
                    b.HasBaseType("WebDbContext.DbEntity.ItemEntity");

                    b.Property<int>("addHp")
                        .HasColumnType("int");

                    b.Property<int>("minAgility")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ArmorEntity");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.MaterialEntity", b =>
                {
                    b.HasBaseType("WebDbContext.DbEntity.ItemEntity");

                    b.Property<int>("countOfMaterials")
                        .HasColumnType("int");

                    b.Property<int>("materialType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MaterialEntity");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.WeaponEntity", b =>
                {
                    b.HasBaseType("WebDbContext.DbEntity.ItemEntity");

                    b.Property<int>("addDmg")
                        .HasColumnType("int");

                    b.Property<int>("minStrong")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("WeaponEntity");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.Modules.BedroomModuleEntity", b =>
                {
                    b.HasBaseType("WebDbContext.DbEntity.Modules.ModuleEntity");

                    b.Property<int>("addMaxHeros")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("BedroomModuleEntity");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.Modules.BusterModuleEntity", b =>
                {
                    b.HasBaseType("WebDbContext.DbEntity.Modules.ModuleEntity");

                    b.HasDiscriminator().HasValue("BusterModuleEntity");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.Modules.EnergyModuleEntity", b =>
                {
                    b.HasBaseType("WebDbContext.DbEntity.Modules.ModuleEntity");

                    b.HasDiscriminator().HasValue("EnergyModuleEntity");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.Modules.MedicalModuleEntity", b =>
                {
                    b.HasBaseType("WebDbContext.DbEntity.Modules.ModuleEntity");

                    b.HasDiscriminator().HasValue("MedicalModuleEntity");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.HeroEntity", b =>
                {
                    b.HasOne("WebDbContext.DbEntity.ArmorEntity", "armor")
                        .WithMany()
                        .HasForeignKey("armorid");

                    b.HasOne("WebDbContext.DbEntity.WeaponEntity", "weapon")
                        .WithMany()
                        .HasForeignKey("weaponid");

                    b.Navigation("armor");

                    b.Navigation("weapon");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.ItemEntity", b =>
                {
                    b.HasOne("WebDbContext.DbEntity.PlayerEntity", null)
                        .WithMany("items")
                        .HasForeignKey("PlayerEntityid");
                });

            modelBuilder.Entity("WebDbContext.DbEntity.PlayerEntity", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
